/*
 * Copyright (C) 2024-2026 FlossWare
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.flossware.jplatform.api;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Message.
 */
class MessageTest {

    @Test
    void testBuilder_validMessage() {
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .payload("Hello".getBytes())
                .header("priority", "high")
                .build();

        assertNotNull(msg.getId());
        assertEquals("test-topic", msg.getTopic());
        assertEquals("app1", msg.getSourceApplicationId());
        assertArrayEquals("Hello".getBytes(), msg.getPayload());
        assertEquals("high", msg.getHeaders().get("priority"));
        assertTrue(msg.getTimestamp() > 0);
    }

    @Test
    void testBuilder_autoGeneratedId() {
        Message msg1 = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .build();

        Message msg2 = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .build();

        assertNotNull(msg1.getId());
        assertNotNull(msg2.getId());
        assertNotEquals(msg1.getId(), msg2.getId());
    }

    @Test
    void testBuilder_customId() {
        Message msg = Message.builder()
                .id("custom-id")
                .topic("test-topic")
                .sourceApplicationId("app1")
                .build();

        assertEquals("custom-id", msg.getId());
    }

    @Test
    void testBuilder_autoGeneratedTimestamp() {
        long before = System.currentTimeMillis();
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .build();
        long after = System.currentTimeMillis();

        assertTrue(msg.getTimestamp() >= before);
        assertTrue(msg.getTimestamp() <= after);
    }

    @Test
    void testBuilder_customTimestamp() {
        long customTimestamp = 1234567890L;
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .timestamp(customTimestamp)
                .build();

        assertEquals(customTimestamp, msg.getTimestamp());
    }

    @Test
    void testBuilder_missingTopic() {
        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> Message.builder()
                        .sourceApplicationId("app1")
                        .build());

        assertTrue(exception.getMessage().contains("topic is required"));
    }

    @Test
    void testBuilder_emptyTopic() {
        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> Message.builder()
                        .topic("")
                        .sourceApplicationId("app1")
                        .build());

        assertTrue(exception.getMessage().contains("topic is required"));
    }

    @Test
    void testBuilder_missingSourceApplicationId() {
        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .build());

        assertTrue(exception.getMessage().contains("sourceApplicationId is required"));
    }

    @Test
    void testBuilder_emptySourceApplicationId() {
        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .sourceApplicationId("")
                        .build());

        assertTrue(exception.getMessage().contains("sourceApplicationId is required"));
    }

    @Test
    void testBuilder_headersMap() {
        Map<String, Object> headers = new HashMap<>();
        headers.put("key1", "value1");
        headers.put("key2", 123);

        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .headers(headers)
                .build();

        assertEquals("value1", msg.getHeaders().get("key1"));
        assertEquals(123, msg.getHeaders().get("key2"));
    }

    @Test
    void testBuilder_incrementalHeaders() {
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .header("key1", "value1")
                .header("key2", "value2")
                .build();

        assertEquals("value1", msg.getHeaders().get("key1"));
        assertEquals("value2", msg.getHeaders().get("key2"));
    }

    @Test
    void testBuilder_headersNullKey() {
        Map<String, Object> headers = new HashMap<>();
        headers.put("validKey", "value");
        headers.put(null, "bad-key");

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .sourceApplicationId("app1")
                        .headers(headers)
                        .build());

        assertTrue(exception.getMessage().contains("headers cannot contain null keys"));
    }

    @Test
    void testBuilder_headersNullValue() {
        Map<String, Object> headers = new HashMap<>();
        headers.put("key1", "value1");
        headers.put("key2", null);

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .sourceApplicationId("app1")
                        .headers(headers)
                        .build());

        assertTrue(exception.getMessage().contains("headers cannot contain null values"));
        assertTrue(exception.getMessage().contains("key2"));
    }

    @Test
    void testBuilder_nullPayload() {
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .payload(null)
                .build();

        assertNull(msg.getPayload());
    }

    @Test
    void testGetHeaders_unmodifiable() {
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .header("key1", "value1")
                .build();

        Map<String, Object> headers = msg.getHeaders();

        assertThrows(UnsupportedOperationException.class,
                () -> headers.put("key2", "value2"));
    }

    @Test
    void testGetPayload_defensiveCopy() {
        byte[] original = "Hello".getBytes();
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .payload(original)
                .build();

        byte[] retrieved = msg.getPayload();
        retrieved[0] = 'X';

        // Original message payload should be unchanged
        assertArrayEquals("Hello".getBytes(), msg.getPayload());
    }

    @Test
    void testBuilder_payloadDefensiveCopy() {
        byte[] original = "Hello".getBytes();
        Message.Builder builder = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .payload(original);

        // Modify original array after passing to builder
        original[0] = 'X';

        // Builder should contain unmodified payload
        Message msg = builder.build();
        assertArrayEquals("Hello".getBytes(), msg.getPayload());
    }

    @Test
    void testBuilder_headersDefensiveCopy() {
        Map<String, Object> originalHeaders = new HashMap<>();
        originalHeaders.put("key1", "value1");

        Message.Builder builder = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .headers(originalHeaders);

        // Modify original map after passing to builder
        originalHeaders.put("key2", "value2");
        originalHeaders.remove("key1");

        // Builder should contain unmodified headers
        Message msg = builder.build();
        assertEquals("value1", msg.getHeaders().get("key1"));
        assertNull(msg.getHeaders().get("key2"));
    }

    @Test
    void testBuilder_headersReplacement() {
        Map<String, Object> headers1 = new HashMap<>();
        headers1.put("key1", "value1");

        Map<String, Object> headers2 = new HashMap<>();
        headers2.put("key2", "value2");

        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .headers(headers1)
                .headers(headers2)
                .build();

        assertNull(msg.getHeaders().get("key1"));
        assertEquals("value2", msg.getHeaders().get("key2"));
    }

    @Test
    void testBuilder_emptyHeaders() {
        Message msg = Message.builder()
                .topic("test-topic")
                .sourceApplicationId("app1")
                .build();

        assertNotNull(msg.getHeaders());
        assertTrue(msg.getHeaders().isEmpty());
    }

    @Test
    void testBuilder_headerNullKey() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .sourceApplicationId("app1")
                        .header(null, "value"));

        assertTrue(exception.getMessage().contains("header key cannot be null"));
    }

    @Test
    void testBuilder_headerNullValue() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .sourceApplicationId("app1")
                        .header("key", null));

        assertTrue(exception.getMessage().contains("header value cannot be null"));
    }

    @Test
    void testBuilder_headersNullKeyInMap() {
        Map<String, Object> headers = new HashMap<>();
        headers.put(null, "value");

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .sourceApplicationId("app1")
                        .headers(headers));

        assertTrue(exception.getMessage().contains("headers cannot contain null keys"));
    }

    @Test
    void testBuilder_headersNullValueInMap() {
        Map<String, Object> headers = new HashMap<>();
        headers.put("testKey", null);

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
                () -> Message.builder()
                        .topic("test-topic")
                        .sourceApplicationId("app1")
                        .headers(headers));

        assertTrue(exception.getMessage().contains("headers cannot contain null values"));
        assertTrue(exception.getMessage().contains("testKey"));
    }
}
